export const CREATE_ADOPT = "CREATE_ADOPT";
export const FETCH_ADOPT = "FETCH_ADOPT";
export const FETCH_SINGLE_ADOPT = "FETCH_SINGLE_ADOPT";
export const DELETE_ADOPT = "DELETE_ADOPT";
export const UPDATE_ADOPT = "UPDATE_ADOPT";